reparoProject/Controllers/LuthierController.cs
using Business;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace reparoProject.Controllers
{
    public class LuthierController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Filtrados()
        {
            return View();
        }

        public ActionResult AnexarFotoLuthier()
        {
            return View();
        }

        public ActionResult AnexarPorId(int id)
        {
            ViewBag.IdDoLuthier = id;
            return View();
        }

        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AnexarFotoLuthier(HttpPostedFileBase file)
        {
            try
            {
                int idDoLuthier = int.Parse(Request["string"]);
                string nomeDoArquivo = "";
                string caminhoDoArquivo = "";

                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles/profilePhotos/luthier"), _FileName);
                    // _FileName = Nome do arquivo
                    // _path = Caminho do arquivo (exemplo: "C:\\Users\\mario\\source\\repos\\freeCommerce\\freeCommerce\\UploadedFiles\\Screenshot_6.png")
                    file.SaveAs(_path);
                    nomeDoArquivo = _FileName;
                    caminhoDoArquivo = _path;
                }
                string dataAgora = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                DateTime dataUploadImg = DateTime.Parse(dataAgora);

                var imagemLuthier = new ImagemLuthier();
                imagemLuthier.idLuthier = idDoLuthier;
                imagemLuthier.nomeImagem = nomeDoArquivo;
                imagemLuthier.caminhoImagem = caminhoDoArquivo;
                imagemLuthier.tipoImg = "Foto de perfil";
                imagemLuthier.Save();
                ViewBag.Message = "File Uploaded Successfully!!";
                Response.Redirect("/autenticacao/minhaconta");
                return View();
            }
            catch (Exception err)
            {
                ViewBag.Message = "File upload failed! " + err.Message;
                return View();
            }
        }

        public ActionResult Perfil(int id)
        {
            var luthier = new Luthier().BuscarPorId(id);
            var dadosDoLuthier = new Luthier().BuscaDadosPorId(id);

            ViewBag.Instrumentos = new Instrumento().Listar();
            ViewBag.Habilidades = new Habilidade().Listar();
            ViewBag.HabilidadesDoLuthier = new HabilidadePorLuthier().ListarPorLuthier(id);
            ViewBag.Servicos = new Servico().Listar();
            ViewBag.Luthier = luthier;
            ViewBag.DadosDoLuthier = dadosDoLuthier;
            return View();
        }

        public ActionResult EditarEndereco(int idLuthier, int idEndereco, string cep, string numero, string logradouro, string bairro, string cidade, string uf)
        {
            var endereco = new Endereco();
            endereco.AtualizarLuthier(idLuthier, idEndereco, cep, numero, logradouro, bairro, cidade, uf);

            JsonResult result = new JsonResult();
            result = this.Json(JsonConvert.SerializeObject(endereco), JsonRequestBehavior.AllowGet);
            return result;
        }
    }
}

reparoProject/Views/Luthier/AnexarFotoLuthier.cshtml
@{
    ViewBag.Title = "Anexar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Feito!

reparoProject/Views/Luthier/AnexarPorId.cshtml
@{
    ViewBag.Title = "Anexar";
    dynamic view = ViewBag.IdDoLuthier;
    int IdDoLuthier = view;
    Layout = "~/Views/Shared/_LayoutAnexo.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<h3 style="margin-top: 10px;">Adicione a imagem do luthier</h3>
@using (Html.BeginForm("AnexarFotoLuthier", "Luthier", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        @Html.TextBox("string", "", new { type = "string" })
        @Html.TextBox("file", "", new { type = "file" }) <br /><br />
        <input class="btn-primary" style="background-color: darkseagreen; border-color: darkseagreen; color: white;" type="submit" value="Atualizar foto de perfil" />
        @ViewBag.Message
    </div>
}

<script>
    jQuery(function ($) {
        $(document).ready(function () {
            document.getElementById('string').style.display = "none";
            document.getElementById('string').value = "@IdDoLuthier";
        });
    });
</script>

reparoProject/Views/Luthier/Filtrados.cshtml
@{
    List<Business.Luthier> luthiersEncontrados = (List<Business.Luthier>)TempData["luthiersPreparados"];
    List<Business.Luthier> luthiersPreparados = new List<Business.Luthier> { };
    int iterador = 0;

    string instrumentoFiltrado = "";
    string servicoFiltrado = "";
    if (TempData["instrumentoBuscado"] != null)
    {
        instrumentoFiltrado = TempData["instrumentoBuscado"].ToString();
    }

    if (TempData["servicoBuscado"] != null)
    {
        servicoFiltrado = TempData["servicoBuscado"].ToString();
    }

    List<Business.LocalLuthier> locaisDosLuthiersEncontrados = new List<Business.LocalLuthier> { };

    if (luthiersEncontrados != null)
    {
        foreach (var prof in luthiersEncontrados)
        {
            var localDoLuthier = new Business.LocalLuthier().BuscaPorLuthier(prof.id);

            if (localDoLuthier.Count > 0)
            {
                locaisDosLuthiersEncontrados.Add(localDoLuthier[0]);
            }
        }
    }

    int qtdLocais = locaisDosLuthiersEncontrados.Count;
    string latitude = "";
    string longitude = "";

    Dictionary<int, string> nomesPorLuthier = new Dictionary<int, string>();
    int idLuthier = 0;

    if (luthiersEncontrados != null)
    {
        foreach (var luthier in luthiersEncontrados)
        {
            var dadosLuthier = new Business.Luthier().BuscarTodasInfoPorId(luthier.id);
            nomesPorLuthier.Add(luthier.id, dadosLuthier[0].nome);
        }
    }

    string latitudeUsuario = "";
    string longitudeUsuario = "";
    if (TempData["latitudeUsuario"] == null)
    {
    }
    else
    {
        latitudeUsuario = TempData["latitudeUsuario"].ToString();
        latitudeUsuario = latitudeUsuario.Replace(",", ".");
        longitudeUsuario = TempData["longitudeUsuario"].ToString();
        longitudeUsuario = longitudeUsuario.Replace(",", ".");
    }
}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin="" />

<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
        crossorigin=""></script>

<style>
    #map {
        height: 600px;
    }


</style>

@{
    if (luthiersEncontrados != null)
    {
        <h1>Luthiers encontrados</h1>
        <h3>@instrumentoFiltrado > @servicoFiltrado</h3>
        if (@luthiersEncontrados.Count == 1)
        {
            <small>1 profissional foi encontrado!</small>
            <br />
            <br />
        }
        else
        {
            <small>@luthiersEncontrados.Count profissionais foram encontrados!</small>
            <br />
            <br />
        }

    }
    else
    {
        <h1>Não foram encontrados profissionais...</h1>
    }
}
<input type="text" id="qtdLocais" name="qtdLocais" value="@qtdLocais" style="display:none;" />

@{
    iterador = 1;
    foreach (var local in locaisDosLuthiersEncontrados)
    {
        latitude = local.latitude.ToString().Replace(",", ".");
        longitude = local.longitude.ToString().Replace(",", ".");
        <input type="text" id="local/@iterador" name="local/@iterador" value="[@latitude,@longitude]" style="display:none;" />
        <input type="text" id="nomeLuthier/@iterador" name="nomeLuthier/@iterador" value="@nomesPorLuthier[local.idLuthier]" style="display:none;" />
        <input type="text" id="luthierId/@iterador" name="luthierId/@iterador" value="@local.idLuthier" style="display:none;" />
        iterador = iterador + 1;
    }
}

<table class="table">
    <tr>
        <td><b>Nome do Luthier</b></td>
        <td><b>Usuário desde</b></td>
        <td><b>Pedidos recebidos</b></td>
        <td><b>Acesso ao perfil do profissional</b></td>
    </tr>
    @{
        if (luthiersEncontrados != null)
        {
            foreach (var luthier in luthiersEncontrados)
            {
                var dadosLuthier = new Business.Luthier().BuscarTodasInfoPorId(luthier.id);
                var qtdPedidosDoLuthier = new Business.Pedido().BuscarPedidoPorLuthier(luthier.id);
                var dataCriacao = dadosLuthier[0].dataCriacao.ToString("dd/MM/yyyy");
                <tr>
                    <td>@dadosLuthier[0].nome</td>
                    <td>@dataCriacao</td>
                    <td>@qtdPedidosDoLuthier.Count</td>
                    <td><a target="_blank" href="/luthier/perfil/@luthier.id" class="btn-sm btn-secondary" style="background: #ffd42a; color: #545255; border: white; ">Clique aqui</a></td>
                </tr>
            }
        }
    }
</table>

<h3>Veja aonde está(ão) o(s) luthier(s) disponível(ís) para esse tipo de serviço abaixo</h3>
<br />


<div id="map"></div>

<script>
    var tileLayer = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png',
        {
            attribution: false
        });

    var map = L.map('map',
        {
            zoomControl: true,
            layers: [tileLayer],
            maxZoom: 18,
            minZoom: 1
        })
        .setView(['@latitudeUsuario', '@longitudeUsuario'], 15);

    setTimeout(function () { map.invalidateSize() }, 800);

    jQuery(function ($) {
        $(document).ready(function () {
            if ('@latitudeUsuario'.length > 1) {
                var marcadorX = L.marker(['@latitudeUsuario', '@longitudeUsuario']).addTo(map);
                marcadorX.bindPopup("Você está (aproximadamente) aqui.").openPopup();
            }
            for (i = 1; i <= document.getElementById('qtdLocais').value; i++) {
                var valores = JSON.parse(document.getElementById('local/' + i).value);
                var latitude = valores[0];
                var longitude = valores[1];
                var nomeDoLuthier = document.getElementById('nomeLuthier/' + i).value;
                var perfilDoLuthier = "perfil/" + document.getElementById('luthierId/' + i).value;
                var meIcon = L.icon({
                    iconUrl: '/UploadedFiles/src/lutIcon.png',
                    shadowUrl: '/UploadedFiles/src/lutIcon-shadow.png',

                    iconSize: [38, 95], // size of the icon
                    shadowSize: [50, 64], // size of the shadow
                    iconAnchor: [22, 94], // point of the icon which will correspond to marker's location
                    shadowAnchor: [4, 62],  // the same for the shadow
                    popupAnchor: [-3, -76] // point from which the popup should open relative to the iconAnchor
                });
                var marcador = L.marker([latitude, longitude], {icon: meIcon}).addTo(map);
                console.log(latitude + "," + longitude);
                marcador.bindPopup("<center><b>Luthier: </b>" + nomeDoLuthier + "<br><b>Perfil</b>: <a target='_blank' href='" + perfilDoLuthier + "'>Acesso ao perfil</a></center>").openPopup();
            }
        });
    });
</script>

reparoProject/Views/Luthier/Perfil.cshtml
@{
    List<Business.Luthier> luthier = ViewBag.Luthier;
    Business.Luthier dadosLuthier = ViewBag.DadosDoLuthier;
    List<Business.Instrumento> instrumentos = ViewBag.Instrumentos;
    List<Business.Habilidade> habilidades = ViewBag.Habilidades;
    List<Business.HabilidadePorLuthier> habilidadesAtualLuthier = ViewBag.HabilidadesDoLuthier;
    List<Business.Servico> todosServicos = ViewBag.Servicos;
    int idDoLuthier = 0;
    int qtdPedidosRecebidos = 0;
    var qtdPedidosDoLuthier = new Business.Pedido().BuscarPedidoPorLuthier(dadosLuthier.id);

    if (luthier != null)
    {
        if (luthier.Count > 0)
        {
            idDoLuthier = luthier[0].id;
        }
    }

    var fotoPerfilLuthierAtual = new Business.ImagemLuthier();
    List<Business.ImagemLuthier> imagensDoAtualLuthier = new Business.ImagemLuthier().ListarTodas();
    foreach (var imagem in imagensDoAtualLuthier)
    {
        if (imagem.idLuthier == dadosLuthier.id && imagem.tipoImg == "Foto de perfil")
        {
            fotoPerfilLuthierAtual = imagem;
        }
    }

    // Encontrando conta logada
    var conta = Business.Conta.BuscaPorStatusLogin(Session.SessionID);
    ViewBag.Conta = conta;
    Business.Conta contaLogada = (Business.Conta)conta;

    // Coletando os dados da última filtragem realizada pelo usuário
    var ultimaFiltragem = Business.UltimaFiltragem.BuscaUltimaFiltragemPorConta(contaLogada.id.ToString());
    Business.UltimaFiltragem lastFiltragemDefinitiva = (Business.UltimaFiltragem)ultimaFiltragem;

    // Coletando servico escolhido pelo usuário
    var idServicoEscolhidoPorUsuario = lastFiltragemDefinitiva.idUltimoServicoPesq;
    var testeLesgo = ViewBag.InstrumentoEscolhido;
    var testeLegoDois = ViewBag.ServicoEscolhido;
    TempData["servFinal"] = idServicoEscolhidoPorUsuario;
    string servicoEscolhidoPorUsuario = "";
    foreach (var ss in todosServicos)
    {
        if (ss.id == idServicoEscolhidoPorUsuario)
        {
            servicoEscolhidoPorUsuario = ss.descricao;
        }
    }

    // Coletando instrumento escolhido pelo usuário
    var idInstrumentoEscolhidoPorUsuario = lastFiltragemDefinitiva.idUltimoInstrumentoPesq;
    TempData["instFinal"] = idInstrumentoEscolhidoPorUsuario;
    string instrumentoEscolhidoPorUsuario = "";
    foreach (var ii in instrumentos)
    {
        if (ii.id == idInstrumentoEscolhidoPorUsuario)
        {
            instrumentoEscolhidoPorUsuario = ii.nome;
        }
    }

    // Habilidade-Serviço
    Dictionary<int, string> servicoPorHabilidade = new Dictionary<int, string>();
    Dictionary<int, string> instrumentoPorHabilidade = new Dictionary<int, string>();
    int idDaHab = 0;
    int idDoServico = 0;
    int idDoInstrumentoDaHab = 0;
    foreach (var skill in habilidades)
    {
        idDoServico = skill.idServico;
        idDaHab = skill.id;
        foreach (var service in todosServicos)
        {
            if (idDoServico == service.id)
            {
                servicoPorHabilidade.Add(idDaHab, service.descricao);
            }
        }
    }
    // Habilidade-Instrumento
    foreach (var habs in habilidades)
    {
        idDoInstrumentoDaHab = habs.idInstrumento;
        idDaHab = habs.id;
        foreach (var inst in instrumentos)
        {
            if (idDoInstrumentoDaHab == inst.id)
            {
                instrumentoPorHabilidade.Add(idDaHab, inst.nome);
            }
        }
    }
}

@if (instrumentoEscolhidoPorUsuario != "" && servicoEscolhidoPorUsuario != "")
{
    <form action="~/pedido/solicitar" method="post">
        <input type="hidden" id="idLuthier" name="idLuthier" value="@dadosLuthier.id" />
        <input type="submit" id="btnSolicitarServico" name="btnSolicitarServico" class="btn btn-secondary" size="55" style="width: 1300px; background: #ffd42a; color: rgba(0,0,0,.5); border: white;" value="Solicitar serviço" />
        <br /><small><u>@instrumentoEscolhidoPorUsuario > @servicoEscolhidoPorUsuario</u> (Este será o serviço que você solicitará caso clique no botão acima, conforme a filtragem que realizou há pouco.)</small>
    </form>
    <br />
}
else
{
    <label>Para contratar algum serviço deste profissional, volte à <a href="/" style="color: #ffd42a">página inicial</a>, realiza a filtragem e escolha @dadosLuthier.nome! &#128516;</label>
}

<div>
    <div style="float:left;">
        <h2><u>Dados do profissional</u></h2>
        <table class="table">
            <tr>
                <td><b>ID (Luthier)</b></td>
                <td><b>Nome do luthier</b></td>
                <td><b>Pedidos recebidos</b></td>
                <td><b>CNPJ</b></td>
                <td><b>CPF</b></td>
                <td><b>Email</b></td>
                <td><b>Foto de perfil</b></td>
            </tr>
            <tr>
                @{
                    string cpfDoLuthier = "********" + Convert.ToString(dadosLuthier.cpf[dadosLuthier.cpf.ToString().Length - 3]) + Convert.ToString(dadosLuthier.cpf[dadosLuthier.cpf.ToString().Length - 2]) + Convert.ToString(dadosLuthier.cpf[dadosLuthier.cpf.ToString().Length - 1]);
                }
                <td>@dadosLuthier.id</td>
                <td>@dadosLuthier.nome</td>
                <td>@qtdPedidosDoLuthier.Count</td>
                <td>@dadosLuthier.cnpj</td>
                <td>@cpfDoLuthier</td>
                <td>@dadosLuthier.email</td>
                <td>
                    @if (fotoPerfilLuthierAtual.caminhoImagem == null || fotoPerfilLuthierAtual.idLuthier == 0 || fotoPerfilLuthierAtual.nomeImagem == null || fotoPerfilLuthierAtual.tipoImg == null)
                    {
                        <label>O Luthier ainda não cadastrou uma foto</label>
                    }
                    else
                    {
                        <img src="~/UploadedFiles/profilePhotos/luthier/@fotoPerfilLuthierAtual.nomeImagem" width="200px" height="200px" />
                    }
                </td>
            </tr>
        </table>
        <br />
    </div>
</div>
<br />

<h2><u>Serviços disponíveis pelo profissional</u></h2>
<table class="table">
    <tr>
        <td><b>Serviço</b></td>
        <td><b>Instrumento alvo</b></td>
    </tr>
    @{
        int teste = 0;
        foreach (var h in habilidadesAtualLuthier)
        {
            <tr>
                <td>@servicoPorHabilidade[h.idHabilidade]</td>
                <td>@instrumentoPorHabilidade[h.idHabilidade]</td>
            </tr>
        }
    }
</table>