reparoProject/Controllers/AutenticacaoController.cs
using Business;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using System.Collections;
using System.Reflection;

namespace freeCommerce.Controllers
{
    public class AutenticacaoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastro()
        {
            return View();
        }

        public ActionResult CadastroCliente()
        {
            return View();
        }

        public ActionResult CadastroLuthier()
        {
            ViewBag.Instrumentos = new Instrumento().Listar();
            ViewBag.Habilidades = new Habilidade().Listar();
            ViewBag.Servicos = new Servico().Listar();
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public void Criar()
        {
            try
            {
                var conta = new Conta();
                conta.usuario = Request["usuario"];
                conta.email = Request["email"];
                conta.senha = Request["senha"];
                conta.Save();
                Response.Redirect("/autenticacao/login");
                TempData["contaCriada"] = "Conta criada com sucesso! Agora você já pode fazer seu login abaixo.";
            }
            catch (Exception erro)
            {
                TempData["contaNaoCriada"] = "A conta não pode ser criada (" + erro.Message + ")!";
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public void CriarCliente()
        {
            try
            {
                var conta = new Conta();
                var contaDois = new Conta();
                conta.usuario = Request["txtUsuario"];
                conta.email = Request["txtEmail"];
                conta.senha = Request["txtSenha"];
                conta.Save();

                var ultimaContaCadastrada = Business.Conta.BuscaUltimoIdCadastrado();
                Business.Conta lastAccountCreated = (Conta)ultimaContaCadastrada;
                var cliente = new Cliente();
                cliente.nome = Request["txtNome"];
                cliente.cpf = Request["txtCpf"];
                cliente.email = Request["txtEmail"];
                cliente.usuario = lastAccountCreated.id;
                cliente.Save();

                var ultimoClienteCadastrado = Cliente.BuscaUltimoClienteCadastrado();
                Business.Cliente lastClientCreated = (Cliente)ultimoClienteCadastrado;
                if(Request["txtCelular"] != null)
                {
                    var celular = new Contato();
                    celular.codigo = Request["txtDddCelular"];
                    celular.numero = Request["txtCelular"];
                    celular.celular = 1;
                    celular.idCliente = lastClientCreated.id;
                    celular.SaveCliente();
                }
                else
                {
                }

                if(Request["txtTelefone"] != null)
                {
                    var telefone = new Contato();
                    telefone.codigo = Request["txtDddTelefone"];
                    telefone.numero = Request["txtTelefone"];
                    telefone.celular = 0;
                    telefone.idCliente = lastClientCreated.id;
                    telefone.SaveCliente();
                }
                else
                {
                }

                var endereco = new Endereco();
                endereco.logradouro = Request["txtLogradouro"];
                endereco.bairro = Request["txtBairro"];
                endereco.cidade = Request["txtCidade"];
                endereco.uf = Request["txtUf"];
                endereco.cep = int.Parse(Request["txtCep"]);
                endereco.numero = int.Parse(Request["txtNumero"]);
                endereco.idElemento = lastClientCreated.id;
                endereco.SaveCliente();

                Response.Redirect("/");
                TempData["contaCriada"] = "Conta criada com sucesso! Agora você já pode fazer seu login abaixo.";
            }
            catch (Exception erro)
            {
                TempData["contaNaoCriada"] = "A conta não pode ser criada (" + erro.Message + ")!";
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public void CriarLuthier()
        {
            try
            {
                var conta = new Conta();
                var contaDois = new Conta();
                conta.usuario = Request["txtUsuario"];
                conta.email = Request["txtEmail"];
                conta.senha = Request["txtSenha"];
                conta.Save();

                var ultimaContaCadastrada = Business.Conta.BuscaUltimoIdCadastrado();
                Business.Conta lastAccountCreated = (Conta)ultimaContaCadastrada;
                var luthier = new Luthier();
                luthier.nome = Request["txtNome"];
                luthier.cpf = Request["txtCpf"];
                luthier.cnpj = Request["txtCnpj"];
                luthier.email = Request["txtEmail"];
                luthier.usuario = lastAccountCreated.id;
                luthier.Save();

                var ultimoLuthierCadastrado = Luthier.BuscaUltimoLuthierCadastrado();
                Business.Luthier lastLuthierCreated = (Luthier)ultimoLuthierCadastrado;
                if (Request["txtCelular"] != "")
                {
                    var celular = new Contato();
                    celular.codigo = Request["txtDddCelular"];
                    celular.numero = Request["txtCelular"];
                    celular.celular = 1;
                    celular.idCliente = lastLuthierCreated.id;
                    celular.SaveLuthier();
                }
                else
                {
                }

                if (Request["txtTelefone"] != "" && Request["txtDddTelefone"] != "")
                {
                    var telefone = new Contato();
                    telefone.codigo = Request["txtDddTelefone"];
                    telefone.numero = Request["txtTelefone"];
                    telefone.celular = 0;
                    telefone.idCliente = lastLuthierCreated.id;
                    telefone.SaveLuthier();
                }
                else
                {
                }

                var endereco = new Endereco();
                endereco.logradouro = Request["txtLogradouro"];
                endereco.bairro = Request["txtBairro"];
                endereco.cidade = Request["txtCidade"];
                endereco.uf = Request["txtUf"];
                var cep = Request["txtCep"];
                cep = cep.Replace("-", "");
                endereco.cep = int.Parse(cep);
                if(Request["txtNumero"] != null)
                {
                    endereco.numero = int.Parse(Request["txtNumero"]);
                }
                else
                {
                    endereco.numero = 0;
                }
                endereco.idElemento = lastLuthierCreated.id;
                endereco.SaveLuthier();

                var localDoLuthier = new LocalLuthier();
                localDoLuthier.idLuthier = lastLuthierCreated.id;
                localDoLuthier.nomeLocal = "Residência";
                localDoLuthier.logradouro = Request["txtLogradouro"];
                localDoLuthier.cidade = Request["txtCidade"];
                localDoLuthier.bairro = Request["txtBairro"];
                localDoLuthier.estado = Request["txtUf"];
                localDoLuthier.longitude = Request["txtLongitude"];
                localDoLuthier.latitude = Request["txtLatitude"];
                localDoLuthier.Salvar();

                string habilidadesDoLuthier = Request["habilidadesSelecionadas"];
                JavaScriptSerializer j = new JavaScriptSerializer();
                object a = j.Deserialize(habilidadesDoLuthier, typeof(object));
                IList listaHabilidadesLuthier = a as IList;
                List<object> listaDois = new List<object> { };

                var listaHabilidades = new List<Habilidade>();
                int iterador = 1;
                foreach (var item in listaHabilidadesLuthier)
                {
                    var habilidade = new Habilidade();
                    Dictionary<string, object> dict = new Dictionary<string, object>() { };
                    dict = (Dictionary<string, object>)item;
                    var foos = dict.Values.ToArray();
                    habilidade.id = iterador;
                    habilidade.idInstrumento = Convert.ToInt32(foos[0]);
                    habilidade.idServico = Convert.ToInt32(foos[1]);
                    listaHabilidades.Add(habilidade);
                    iterador = iterador + 1;
                }

                var listaFinal = new List<Habilidade>();
                foreach (var habilidadeFinal in listaHabilidades)
                {
                    var habilidadeLuthier = new Habilidade();
                    habilidadeLuthier = habilidadeLuthier.BuscarPorInstAndServ(habilidadeFinal.idInstrumento, habilidadeFinal.idServico);
                    listaFinal.Add(habilidadeLuthier);
                }

                foreach(var habDoLuthier in listaFinal)
                {
                    var especialidadeLuthier = new HabilidadePorLuthier();
                    especialidadeLuthier.idLuthier = lastLuthierCreated.id;
                    especialidadeLuthier.idHabilidade = habDoLuthier.id;
                    especialidadeLuthier.Salvar();
                }

                Response.Redirect("/");

reparoProject/Views/Shared/_Layout.cshtml
@{
    string usuarioLogado = "";
    string idDaSessao = Session.SessionID;
    string crieOuLogin = "Crie sua conta ou faça login";
    string bemVindo = "Olá, ";
    string contaTeste = "";
    contaTeste = ViewBag.PosDesconexao;
    if (Html.Action("UsuarioLogado", "Autenticacao") == null)
    {
        usuarioLogado = "";
    }
    else
    {
        usuarioLogado = Html.Action("UsuarioLogado", "Autenticacao").ToString();
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js" type="text/javascript"></script>

    <link rel="stylesheet" href="~/Style/components.css" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!-- Bootstrap's Imports -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <style>
        .jumbotron {
            position: relative;
            /*background: none;*/
            background: #ffd42a;
        }

        body {
            font-family: "roboto-regular", Verdana;
        }

        .navbar {
            transition: all 0.4s;
            top: -50px;
        }

            .navbar .nav-link {
                color: #fff;
            }

        .jumbotron:after {
            content: "";
            display: block;
            position: absolute;
            top: 0;
            left: 0;
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
            width: 100%;
            height: 100%;
            opacity: 0.2;
            z-index: -1;
        }

        .carousel-control-prev-icon {
            background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23ffd42a' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E") !important;
        }

        .carousel-control-next-icon {
            background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23ffd42a'  viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E") !important;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-radius: 30px; margin: 5px; padding: 4px; background-color: #337ab7; border-color: #337ab7; color: white;">
        <a class="navbar-brand" href="/" style="margin-top: 7px; margin-left: 50px">
            <img style="margin-top: -10px;" src="~/UploadedFiles/src/logo.png" alt="" width="30" height="70" class="d-inline-block align-text-top">
            &nbsp;
        </a>
        <button style="margin-right: 15px;" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-right:50px;">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @{
                            if (usuarioLogado.Length < 1)
                            {
                                @crieOuLogin;
                            }
                            else
                            {
                                @bemVindo; <b>@usuarioLogado</b>
                            }
                        }
                    </a>
                    @{
                        if (usuarioLogado.Length < 1)
                        {
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="/autenticacao/cadastro">Criar conta</a>
                                <a class="dropdown-item" href="/autenticacao/login">Fazer login</a>
                            </div>
                        }
                        else
                        {
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="/autenticacao/minhaconta">Minha conta</a>
                                <a class="dropdown-item" onclick="desconectaUsuario()" href="/">Desconectar</a>
                            </div>
                        }
                    }
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/admin/portal">Administrador</a>
                </li>
                <li>
                    <a class="nav-link" href="/">Procurar profissionais</a>
                </li>
            </ul>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <div>
                            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="margin-top: -20px;">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img src="" style="margin-top: -20px;" src="~/UploadedFiles/src/default.png" id="imagemTemperatura" name="imagemTemperatura" alt="" width="40" height="34" class="d-inline-block align-text-top">
                                        <label style="color: #545255; margin-top: 10px; " id="gioiaMario" name="gioiaMario"></label>
                                    </div>
                                    <div class="carousel-item">
                                        <img src="" style="margin-top: -20px;" src="~/UploadedFiles/src/default.png" id="imagemTemperaturaDois" name="imagemTemperaturaDois" alt="" width="40" height="34" class="d-inline-block align-text-top">
                                        <label style="color: #545255; margin-top: 10px; " id="gioiaMarioDois" name="gioiaMarioDois"></label>
                                    </div>
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true" style="margin-top: 60px;"></span>
                                    <span class="sr-only">Anterior</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true" style="margin-top:60px;"></span>
                                    <span class="sr-only">Próximo</span>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="~/UploadedFiles/src/logo.png" alt="" width="30" height="70" class="d-inline-block align-text-top">
                            @{
                                if (usuarioLogado.Length < 1)
                                {

                                    @crieOuLogin;
                                }
                                else
                                {
                                    @bemVindo; <b>@usuarioLogado</b>
                                }
                            }
                        </a>
                        @{
                            if (usuarioLogado.Length < 1)
                            {
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/autenticacao/cadastro">Criar conta</a>
                                    <a class="dropdown-item" href="/autenticacao/login">Fazer login</a>
                                </div>
                            }
                            else
                            {
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/autenticacao/minhaconta">Minha conta</a>
                                    <a class="dropdown-item" onclick="desconectaUsuario()" href="/">Desconectar</a>
                                </div>
                            }
                        }
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {
        $(window).scroll(function () {
            var scroll = $(window).scrollTop();
            //>=, not <=
            /*if (scroll >= 60) {
                //clearHeader, not clearheader - caps H
                $(".navbar").addClass("bg-light");
            } else {
                $(".navbar").removeClass("bg-light");
            }*/
        }); //missing );
        // document ready
    });

    function desconectaUsuario() {
        $.ajax({
                type: "POST",
                url: '@Url.Action("Desconecta", "Autenticacao")',
                data: '',
                contentType: "application/json; charset=utf-8",
                success: function () {
                    console.log("Desconectado!");
                },
                error: function () {
                    console.log("Sistema tentou localizar uma View para o ActionResult Desconecta, mas ele não existe. Usuário desconectado da mesma forma!");
                }
            });
    }

    jQuery(function ($) {
        $(document).ready(function () {
            var cidade = "Sao Paulo";
            $.get("http://api.weatherapi.com/v1/current.json?key=6ff526e40a4f47b4834125549220405&q=" + cidade + "&aqi=no", { code: cidade }, function (resultado) {
                console.log(resultado);
                document.getElementById("imagemTemperatura").src = resultado.current.condition.icon;
                document.getElementById('gioiaMario').innerHTML = resultado.location.name + ", " + resultado.location.region + "<br />" + resultado.current.temp_c + "ºC"  ;
            });
        });
    });

    jQuery(function ($) {
        $(document).ready(function () {
            var cidade = "Rio de Janeiro";
            $.get("http://api.weatherapi.com/v1/current.json?key=6ff526e40a4f47b4834125549220405&q=" + cidade + "&aqi=no", { code: cidade }, function (resultado) {
                console.log(resultado);
                document.getElementById("imagemTemperaturaDois").src = resultado.current.condition.icon;
                document.getElementById('gioiaMarioDois').innerHTML = resultado.location.name + ", " + resultado.location.region + "<br />" + resultado.current.temp_c + "ºC";
            });
        });
    });
</script>

reparoProject/Views/Shared/_LayoutAnexo.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .jumbotron {
            position: relative;
            /*background: none;*/
            background: #CF95F2;
        }

        .navbar {
            transition: all 0.4s;
        }

            .navbar .nav-link {
                color: #fff;
            }

        .jumbotron:after {
            content: "";
            display: block;
            position: absolute;
            top: 0;
            left: 0;
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
            width: 100%;
            height: 100%;
            opacity: 0.2;
            z-index: -1;
        }
    </style>
</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <br />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>