reparoProject/Controllers/ClienteController.cs
using Business;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace reparoProject.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult AnexarFotoCliente()
        {
            return View();
        }

        public ActionResult AnexarPorId(int id)
        {
            ViewBag.IdDoCliente = id;
            return View();
        }

        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AnexarFotoCliente(HttpPostedFileBase file)
        {
            try
            {
                int idDoCliente = int.Parse(Request["string"]);
                string nomeDoArquivo = "";
                string caminhoDoArquivo = "";

                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles/profilePhotos/cliente"), _FileName);
                    // _FileName = Nome do arquivo
                    // _path = Caminho do arquivo (exemplo: "C:\\Users\\mario\\source\\repos\\freeCommerce\\freeCommerce\\UploadedFiles\\Screenshot_6.png")
                    file.SaveAs(_path);
                    nomeDoArquivo = _FileName;
                    caminhoDoArquivo = _path;
                }
                string dataAgora = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                DateTime dataUploadImg = DateTime.Parse(dataAgora);

                var imagemDeCliente = new ImagemCliente();
                imagemDeCliente.idCliente = idDoCliente;
                imagemDeCliente.nomeImagem = nomeDoArquivo;
                imagemDeCliente.caminhoImagem = caminhoDoArquivo;
                imagemDeCliente.tipoImg = "Foto de perfil";
                imagemDeCliente.Save();

                /*var produto = new Item();
                produto.id = 4;
                produto.imgPath = caminhoDoArquivo;
                produto.imgFile = nomeDoArquivo;
                produto.SalvarImg();*/
                ViewBag.Message = "File Uploaded Successfully!!";
                Response.Redirect("/autenticacao/minhaconta");
                return View();
            }
            catch (Exception err)
            {
                ViewBag.Message = "File upload failed! " + err.Message;
                return View();
            }
        }
        public ActionResult EditarEndereco(int idCliente, int idEndereco, string cep, string numero, string logradouro, string bairro, string cidade, string uf)
        {
            var endereco = new Endereco();
            endereco.AtualizarCliente(idCliente, idEndereco, cep, numero, logradouro, bairro, cidade, uf);

            JsonResult result = new JsonResult();
            result = this.Json(JsonConvert.SerializeObject(endereco), JsonRequestBehavior.AllowGet);
            return result;
        }
    }
}

reparoProject/Views/Cliente/AnexarFotoCliente.cshtml
@{
    ViewBag.Title = "Anexar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Feito!

reparoProject/Views/Cliente/AnexarPorId.cshtml
@{
    ViewBag.Title = "Anexar";
    List<Business.Cliente> ultimoId = ViewBag.UltimoIdRegistrado;
    dynamic view = ViewBag.IdDoCliente;
    int idDoCliente = view;
    Layout = "~/Views/Shared/_LayoutAnexo.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<h3 style="margin-top: 10px;">Adicione a imagem do cliente</h3>
@using (Html.BeginForm("AnexarFotoCliente", "Cliente", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        @Html.TextBox("string", "", new { type = "string" })
        @Html.TextBox("file", "", new { type = "file" }) <br /><br />
        <input class="btn-primary" style="background-color: darkseagreen; border-color: darkseagreen; color: white;" type="submit" value="Atualizar foto de perfil" />
        @ViewBag.Message
    </div>
}

<script>
    jQuery(function ($) {
        $(document).ready(function () {
            document.getElementById('string').style.display = "none";
            document.getElementById('string').value = "@idDoCliente";
        });
    });
</script>